---

- hosts: all
  handlers:
  - include: handlers/main.yml
  roles:
  - role: rethinkdb_common

- hosts: rethinkdb_serve_hosts
  roles:
  - role: rethinkdb_serve
  - { role: rethinkdb_sshtunnel, when: "rethinkdb_sshtunnel" }

- hosts: rethinkdb_proxy_hosts
  roles:
  - role: rethinkdb_proxy
  - { role: rethinkdb_sshtunnel, when: "rethinkdb_sshtunnel" }

